export default data = [
  {
    row: "A",
    seats: [
      { num: 1,status:'available' }, 
      { num: 2,status:'available' },
      { num: 3,status:'available' },
      { num: 4,status:'available' },
      { num: 5,status:'available' },
      { num: 6 ,status:'available'},
      { num: 7,status:'available' },
      { num: 8,status:'available' },
      { num: 9,status:'available' },
      { num: 10,status:'available' },
      { num: 11,status:'available' }, 
      { num: 12,status:'available' },
      { num: 13,status:'available' },
      { num: 14,status:'available' },
      { num: 15,status:'available' },
      { num: 16,status:'available' },
      { num: 17,status:'available' },
      { num: 18,status:'available' },
      { num: 19,status:'available' },
      { num: 20,status:'available' },
    ]
  },
  {
    row: "B",
    seats: [
      { num: 1,status:'available' }, 
      { num: 2,status:'available' },
      { num: 3,status:'available' },
      { num: 4,status:'available' },
      { num: 5,status:'available' },
      { num: 6 ,status:'available'},
      { num: 7,status:'available' },
      { num: 8,status:'available' },
      { num: 9,status:'available' },
      { num: 10,status:'available' },
      { num: 11,status:'available' }, 
      { num: 12,status:'available' },
      { num: 13,status:'available' },
      { num: 14,status:'available' },
      { num: 15,status:'available' },
      { num: 16,status:'available' },
      { num: 17,status:'available' },
      { num: 18,status:'available' },
      { num: 19,status:'available' },
      { num: 20,status:'available' },
    ]
  },
  {
    row: "C",
    seats: [
      { num: 1,status:'available' }, 
      { num: 2,status:'available' },
      { num: 3,status:'available' },
      { num: 4,status:'available' },
      { num: 5,status:'available' },
      { num: 6 ,status:'available'},
      { num: 7,status:'available' },
      { num: 8,status:'available' },
      { num: 9,status:'available' },
      { num: 10,status:'available' },
      { num: 11,status:'available' }, 
      { num: 12,status:'available' },
      { num: 13,status:'available' },
      { num: 14,status:'available' },
      { num: 15,status:'available' },
      { num: 16,status:'available' },
      { num: 17,status:'available' },
      { num: 18,status:'available' },
      { num: 19,status:'available' },
      { num: 20,status:'available' },
    ]
  },
  {
    row: "D",
    seats: [
      { num: 1,status:'available' }, 
      { num: 2,status:'available' },
      { num: 3,status:'available' },
      { num: 4,status:'available' },
      { num: 5,status:'available' },
      { num: 6 ,status:'available'},
      { num: 7,status:'available' },
      { num: 8,status:'available' },
      { num: 9,status:'available' },
      { num: 10,status:'available' },
      { num: 11,status:'available' }, 
      { num: 12,status:'available' },
      { num: 13,status:'available' },
      { num: 14,status:'available' },
      { num: 15,status:'available' },
      { num: 16,status:'available' },
      { num: 17,status:'available' },
      { num: 18,status:'available' },
      { num: 19,status:'available' },
      { num: 20,status:'available' },
    ]
  },
  {
    row: "E",
    seats: [
      { num: 1,status:'available' }, 
      { num: 2,status:'available' },
      { num: 3,status:'available' },
      { num: 4,status:'available' },
      { num: 5,status:'available' },
      { num: 6 ,status:'available'},
      { num: 7,status:'available' },
      { num: 8,status:'available' },
      { num: 9,status:'available' },
      { num: 10,status:'available' },
      { num: 11,status:'available' }, 
      { num: 12,status:'available' },
      { num: 13,status:'available' },
      { num: 14,status:'available' },
      { num: 15,status:'available' },
      { num: 16,status:'available' },
      { num: 17,status:'available' },
      { num: 18,status:'available' },
      { num: 19,status:'available' },
      { num: 20,status:'available' },
    ]
  },
  {
    row: "F",
    seats: [
      { num: 1,status:'available' }, 
      { num: 2,status:'available' },
      { num: 3,status:'available' },
      { num: 4,status:'available' },
      { num: 5,status:'available' },
      { num: 6 ,status:'available'},
      { num: 7,status:'available' },
      { num: 8,status:'booked' },
      { num: 9,status:'booked' },
      { num: 10,status:'booked' },
      { num: 11,status:'booked' }, 
      { num: 12,status:'booked' },
      { num: 13,status:'available' },
      { num: 14,status:'available' },
      { num: 15,status:'available' },
      { num: 16,status:'available' },
      { num: 17,status:'booked' },
      { num: 18,status:'booked' },
      { num: 19,status:'available' },
      { num: 20,status:'available' },
    ]
  },
  {
    row: "G",
    seats: [
      { num: 1,status:'available' }, 
      { num: 2,status:'available' },
      { num: 3,status:'available' },
      { num: 4,status:'available' },
      { num: 5,status:'available' },
      { num: 6,status:'booked'},
      { num: 7,status:'booked' },
      { num: 8,status:'booked' },
      { num: 9,status:'booked' },
      { num: 10,status:'available' },
      { num: 11,status:'available' }, 
      { num: 12,status:'available' },
      { num: 13,status:'available' },
      { num: 14,status:'available' },
      { num: 15,status:'booked' },
      { num: 16,status:'booked' },
      { num: 17,status:'booked' },
      { num: 18,status:'available' },
      { num: 19,status:'available' },
      { num: 20,status:'available' },
    ]
  },
  {
    row: "I",
    seats: [
      { num: 1,status:'available' }, 
      { num: 2,status:'booked' },
      { num: 3,status:'available' },
      { num: 4,status:'available' },
      { num: 5,status:'available' },
      { num: 6 ,status:'available'},
      { num: 7,status:'booked' },
      { num: 8,status:'booked' },
      { num: 9,status:'booked' },
      { num: 10,status:'available' },
      { num: 11,status:'available' }, 
      { num: 12,status:'available' },
      { num: 13,status:'available' },
      { num: 14,status:'available' },
      { num: 15,status:'available' },
      { num: 16,status:'available' },
      { num: 17,status:'available' },
      { num: 18,status:'available' },
      { num: 19,status:'available' },
      { num: 20,status:'available' },
    ]
  },
  {
    row: "J",
    seats: [
      { num: 1,status:'available' }, 
      { num: 2,status:'booked' },
      { num: 3,status:'available' },
      { num: 4,status:'available' },
      { num: 5,status:'available' },
      { num: 6 ,status:'available'},
      { num: 7,status:'booked' },
      { num: 8,status:'booked' },
      { num: 9,status:'booked' },
      { num: 10,status:'available' },
      { num: 11,status:'available' }, 
      { num: 12,status:'available' },
      { num: 13,status:'available' },
      { num: 14,status:'available' },
      { num: 15,status:'available' },
      { num: 16,status:'available' },
      { num: 17,status:'available' },
      { num: 18,status:'available' },
      { num: 19,status:'available' },
      { num: 20,status:'available' },
    ]
  },
  {
    row: "K",
    seats: [
      { num: 1,status:'available' }, 
      { num: 2,status:'booked' },
      { num: 3,status:'available' },
      { num: 4,status:'available' },
      { num: 5,status:'available' },
      { num: 6 ,status:'available'},
      { num: 7,status:'booked' },
      { num: 8,status:'booked' },
      { num: 9,status:'booked' },
      { num: 10,status:'available' },
      { num: 11,status:'available' }, 
      { num: 12,status:'available' },
      { num: 13,status:'available' },
      { num: 14,status:'available' },
      { num: 15,status:'available' },
      { num: 16,status:'available' },
      { num: 17,status:'available' },
      { num: 18,status:'available' },
      { num: 19,status:'available' },
      { num: 20,status:'available' },
    ]
  },
];
