# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'page' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Auth'
  # Pods for page

#pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
#pod 'RNI18n', :path => '../node_modules/react-native-i18n'
#pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
#pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
#pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

# this is very important to have!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  target 'pageTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'page-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for page-tvOS

  target 'page-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
