# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'page' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Auth'
  # Pods for page

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'pageTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'page-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for page-tvOS

  target 'page-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
